server:
 port: 9100
 context-path: /inter
httpServer:
  caseServer: http://192.168.1.122:9200/case/
  user:
    baseUrl: http://192.168.1.123:9090
    roleUrlpath: /user/getRoleUrlPathBySystem?system=group
spring:
  redis:
    host: 192.168.1.121
    port: 6379
    timeout: 20000
  session:
    store-type: redis
  datasource:
    url: jdbc:mysql://192.168.1.121:3306/testingplatform?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Imobpay123456!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

codePath: codes
apidocPath: apidocs
checkReportPath: checkReport
jacocoReportPath: jacocoReport

jacocoDumpath: jacocoDump
classFilePath: classFile
mvnPath: /usr/local/src/apache-maven-3.5.3/bin/mvn
firelineJarPath: /usr/local/lib/fireline_1.4.10.jar
JAVA_HOME: /usr/bin/java

ignore:
  urlPath:
  ip: 192.168.1.120,192.168.1.121,192.168.1.122,192.168.1.123