server:
 port: 9090
 context-path: /inter
httpServer:
  caseServer: http://192.168.1.49:9090/case/
  user:
    baseUrl: http://192.168.1.44:9090
    roleUrlpath: /user/getRoleUrlPathBySystem?system=group
    
spring:
  redis:
    host: 192.168.1.46
#    host: 127.0.0.1
    port: 6379
    timeout: 20000
  session:
    store-type: redis
  datasource:
    url: jdbc:mysql://192.168.1.42:3306/testingplatform?useUnicode=true&amp;characterEncoding=utf-8
#    url: jdbc:mysql://127.0.0.1:3306/platform?useUnicode=true&amp;characterEncoding=utf-8
    username: tester
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

codePath: codes
apidocPath: apidocs

ignore:
  urlPath:
  ip: 192.168.1.43,192.168.1.44,192.168.1.47,192.168.1.49