server:
 port: 9100
# context-path: /inter
httpServer:
  caseServer: http://127.0.0.1:9200/case/
  user:
    baseUrl: http://127.0.0.1:9090
    roleUrlpath: /user/getRoleUrlPathBySystem?system=group
spring:
  redis:
    host: 192.168.1.121
    port: 6379
    timeout: 20000
  session:
    store-type: redis
  datasource:
    url: jdbc:mysql://192.168.1.121:3306/testingplatform?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Imobpay123456!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: 192.168.1.121
    port: 5672
    username: rabbitadmin
    password: 123456
  application:
    name: platform-interface
  cloud:
    config:
      label: master
      profile: prod
      discovery:
       enabled: true
       serviceId: PLATFORM-CONFIG-SERVER
#eureka:
# client:
#  serviceUrl:
#   defaultZone: http://192.168.1.121:9400/eureka/
management:
  security:
    enabled: false
feign:
  httpclient:
    enabled: true
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000
#logging:
#  level:
#    ROOT: DEBUG

codePath: codes
apidocPath: apidocs
checkReportPath: checkReport
jacocoReportPath: jacocoReport

jacocoDumpath: jacocoDump
classFilePath: classFile
mvnPath: /usr/local/src/apache-maven-3.5.3/bin/mvn
firelineJarPath: /home/ted/project/jar/fireline_1.6.10.jar
JAVA_HOME: /home/ted/jdk1.8.0_141

ignore:
  urlPath:
  ip: 127.0.0.1,192.168.18.140